### ISSUE TITLE
Resource not compiled

### ISSUE THREAD

**Issue by martindobias** [brian428/grails-coffeescript-compiler-plugin#4] opened 2013-02-24 19:03 UTC
During initialization my resource is not compiled.

My coffee resource is only one line (just to test the functionality) and is located at src/coffee/app:
alert "Hello CoffeeScript!"

Config.groovy contains:
"coffeescript-compiler" {

```
appSource {
    coffeeSourcePath = "src/coffee/app"
    jsOutputPath = "web-app/js/app"
}

testSource {
    coffeeSourcePath = "src/coffee/spec"
    jsOutputPath = "web-app/js/spec"
}
```

}

An empty js file is generated at web-app/js/app and there is such output on stderr:
2013-02-24 19:54:51,742 [main] INFO  compiler.CoffeeCompilerManager  - Compiling CoffeeScript path src/coffee/app to web-app/js/app
2013-02-24 19:54:51,814 [main] INFO  compiler.CoffeeCompiler  - Purging web-app/js/app...
| Error 2013-02-24 19:54:52,732 [pool-4-thread-1] ERROR compiler.CoffeeCompiler  - null in src\coffee\app\user_index.coffee

The error is the same no matter what is the content of my coffee script file.

I do not have node.js installed

Please help, thanks

**Comment by brian428** [comment] 2013-02-24 19:10
Please attach the actual file that is not compiling.

**Comment by martindobias** [comment] 2013-02-24 23:21
Can't really attach here, so here are some links:
https://gist.github.com/martindobias/49737e98feb48b0d5a92
http://dl.dropbox.com/u/10057117/user_index.coffee

But as I said, it does not matter on what is inside the file. I have tried many different files, all syntax-wise OK according to http://coffeescript.org/ [TRY COFFEESCRIPT]

**Comment by brian428** [comment] 2013-02-25 03:15
Try 0.8, which I just published. Looks like there was an issue when using Rhino (not Node), but since I have Node installed I wasn't seeing the error. I added tests to confirm things work on both Rhino and Node. Thanks.

**Comment by martindobias** [comment] 2013-02-25 07:00
Unfortunatelly that did not help me.
I have managed to get the stacktrace by modifying your code:

java.lang.reflect.MalformedParameterizedTypeException

[sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl.validateConstructorArguments(ParameterizedTypeImpl.java:60),
 sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl.<init>(ParameterizedTypeImpl.java:53),
 sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl.make(ParameterizedTypeImpl.java:95),
 sun.reflect.generics.factory.CoreReflectionFactory.makeParameterizedType(CoreReflectionFactory.java:105),
 sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:140),
 sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49),
 sun.reflect.generics.repository.ConstructorRepository.getParameterTypes(ConstructorRepository.java:94),
 java.lang.reflect.Method.getGenericParameterTypes(Method.java:291),
 java.beans.FeatureDescriptor.getParameterTypes(FeatureDescriptor.java:387),
 java.beans.MethodDescriptor.setMethod(MethodDescriptor.java:114),
 java.beans.MethodDescriptor.<init>(MethodDescriptor.java:72),
 java.beans.MethodDescriptor.<init>(MethodDescriptor.java:56),
 java.beans.Introspector.getTargetMethodInfo(Introspector.java:1131),
 java.beans.Introspector.getBeanInfo(Introspector.java:414),
 java.beans.Introspector.getBeanInfo(Introspector.java:161),
 groovy.lang.MetaClassImpl$15.run(MetaClassImpl.java:2944),
 java.security.AccessController.doPrivileged(Native Method),
 groovy.lang.MetaClassImpl.addProperties(MetaClassImpl.java:2942),
 groovy.lang.MetaClassImpl.initialize(MetaClassImpl.java:2925),
 groovy.lang.ExpandoMetaClass.initialize(ExpandoMetaClass.java:483),
 org.codehaus.groovy.reflection.ClassInfo.getMetaClassUnderLock(ClassInfo.java:176),
 org.codehaus.groovy.reflection.ClassInfo.getMetaClass(ClassInfo.java:192),
 org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.getMetaClass(MetaClassRegistryImpl.java:309),
 org.codehaus.groovy.runtime.InvokerHelper.getMetaClass(InvokerHelper.java:806),
 org.codehaus.groovy.runtime.callsite.CallSiteArray.createCallConstructorSite(CallSiteArray.java:84),
 org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:57),
 org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:182),
 org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:190),
 org.grails.plugins.coffee.compiler.processor.RhinoCoffeeScriptProcessor.<init>(RhinoCoffeeScriptProcessor.groovy:23),
 sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method),
 sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57),
 sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45),
 java.lang.reflect.Constructor.newInstance(Constructor.java:525),
 org.springsource.loaded.ri.ReflectiveInterceptor.jlrConstructorNewInstance(ReflectiveInterceptor.java:975),
 org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:77),
 org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:102),
 org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:57),
 org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:182),
 org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:190),
 org.grails.plugins.coffee.compiler.processor.CoffeeScriptProcessor$1.initialize(CoffeeScriptProcessor.groovy:100),
 org.grails.plugins.coffee.compiler.processor.CoffeeScriptProcessor$1.initialize(CoffeeScriptProcessor.groovy),
 ro.isdc.wro.util.LazyInitializer.get(LazyInitializer.java:32),
 ro.isdc.wro.model.resource.processor.decorator.LazyProcessorDecorator.getProcessorDecorator(LazyProcessorDecorator.java:43),
 ro.isdc.wro.model.resource.processor.decorator.LazyProcessorDecorator.process(LazyProcessorDecorator.java:54),
 ro.isdc.wro.model.resource.processor.ResourcePreProcessor$process$0.call(Unknown Source),
 org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45),
 org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108),
 org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:124),
 org.grails.plugins.coffee.compiler.processor.CoffeeScriptProcessor.process(CoffeeScriptProcessor.groovy:68),
 ro.isdc.wro.model.resource.processor.ResourcePreProcessor$process.call(Unknown Source),
 org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45),
 org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:108),
 org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:124),
 org.grails.plugins.coffee.compiler.CoffeeCompiler.compileFile(CoffeeCompiler.groovy:68),
 sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method),
 sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57),
 sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43),
 java.lang.reflect.Method.invoke(Method.java:601),
 org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1243),
 org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90),
 groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233),
 groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1076),
 groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1110),
 groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:906),
 groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1021),
 groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1110),
 groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:906),
 groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:727),
 groovy.lang.GroovyObjectSupport.invokeMethod(GroovyObjectSupport.java:44),
 org.grails.plugins.coffee.compiler.CoffeeCompiler$_compileAll_closure2.invokeMethod(CoffeeCompiler.groovy),
 groovy.lang.MetaClassImpl.invokeMethodOnGroovyObject(MetaClassImpl.java:1141),
 groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035),
 groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1110),
 groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:906),
 org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:66),
 org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:49),
 org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:133),
 org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:153),
 org.grails.plugins.coffee.compiler.CoffeeCompiler$_compileAll_closure2_closure6.doCall(CoffeeCompiler.groovy:129),
 org.grails.plugins.coffee.compiler.CoffeeCompiler$_compileAll_closure2_closure6.doCall(CoffeeCompiler.groovy),
 sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method),
 sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57),
 sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43),
 java.lang.reflect.Method.invoke(Method.java:601),
 org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1243),
 org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90),
 groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:233),
 groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1076),
 groovy.lang.ExpandoMetaClass.invokeMethod(ExpandoMetaClass.java:1110),
 groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:906),
 groovy.lang.Closure.call(Closure.java:415),
 org.grails.plugins.coffee.compiler.CoffeeCompiler$_compileAll_closure2_closure6.call(CoffeeCompiler.groovy),
 groovy.lang.Closure.call(Closure.java:409),
 org.grails.plugins.coffee.compiler.CoffeeCompiler$_compileAll_closure2_closure6.call(CoffeeCompiler.groovy),
 java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334),
 java.util.concurrent.FutureTask.run(FutureTask.java:166),
 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110),
 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603),
 java.lang.Thread.run(Thread.java:722)]

**Comment by brian428** [comment] 2013-02-25 07:23
I'm not really sure what's going on then. I made another tweak so see if 0.8.1 helps. If not, I may need to see if you can zip up a simple app that demonstrates the issue, because I've now got tests that run using both the Rhino and the Node compiler and both sets of tests run successfully. Just to check, what JRE version and Grails version are you using? Do you have any other plugins installed that might be conflicting with this one?

**Comment by ctoestreich** [comment] 2013-02-25 07:38
I am ooo until a week from tomorrow.   I can help once I get back since this is probably related to my pull req.

**Comment by martindobias** [comment] 2013-02-25 08:34
Created a simple app, I hope I managed to get rid of all dependencies to my code

https://github.com/martindobias/RhinoTest
Same behavior

**Comment by brian428** [comment] 2013-02-25 14:08
Thanks, I'll take a look. 

@ctowstreich, I did run into one issue with the processor, it looked like the Rhino LazyProcessorDecorator wasn't castable to ProcessorDecorator (which Node uses), so I just removed the type info and used def, which seems to work. But I also added a static property to force it to Rhino and added tests to use Rhino, and these all pass for me, so I'm not sure what's going on.

**Comment by brian428** [comment] 2013-02-25 14:14
Also, Martin, just for fun, if you haven't done it, can you do a full grails clean and grails compile, then give it a shot? It may not matter, but I've also seen Grails get hung up on Config changes until you purge everything and rebuild it.

**Comment by martindobias** [comment] 2013-02-25 14:20
This will not be my case. I did created RhinoTest this morning from scratch. So there was no old junk or anything.

**Comment by brian428** [comment] 2013-02-26 00:53
I see your app is using Grails 1.6, which is several years old. This plugin was designed for Grails 2.x, so I'm fairly sure that's your problem. Plugin design changed fairly extensively in 2.0. Your app ran fine and compiled through the Rhino processor on my local setup (Grails 2.1) and the most recent plugin version (0.8.1).

Since it's almost certainly the outdated version of Grails, I'm going to close this. If you like, try it with the latest version of Grails, and if it still doesn't work, let me know so I can reopen. Thanks.

**Comment by martindobias** [comment] 2013-02-26 06:56
Brian, how did you came to this conclusion? I use Grails 2.2.0.

I have searched RhinoTest source files for string 1.6 to check whether there is something not forgotten and found it only in [BuildConfig.groovy](https://github.com/martindobias/RhinoTest/blob/master/grails-app/conf/BuildConfig.groovy)
But this is a JDK level to be used, not grails version.

My setup is
JDK 1.7.0-07 64bit
Grails 2.2.0
Windows 8 64bit

I am still interested in comments from ctowstreich, perhaps he can help me.

I would also try to debug the case to try to find out what is wrong. Unfortunately I am not experienced in Rhino and its interoperability from Groovy. I would really appreciate some help how to reproduce the case in separate environment without Grails perhaps. Then I could contribute back to your plugin.

**Comment by martindobias** [comment] 2013-02-26 09:44
OK, tried the very same code on different computer:
JDK 1.7.0-13 64bit
Grails 2.2.0
Windows 7 64bit

This time everything works.
I do not think the reason is different JDK, so it is Windows 8 to blame.
Anyway I still need to fix the issue

Any idea what might be wrong?

**Comment by martindobias** [comment] 2013-02-26 09:54
Sorry, my fault.
Reproduced even on that computer. It was working because there was node.js and coffee-script installed. Once uninstalled the compiler switched back to Rhino and the problem is back.

So it is still present on 2 different computers

**Comment by martindobias** [comment] 2013-02-26 10:01
By the way, when I have switched to version 0.8.1 I got following error.
It seems that 0.8.1 is not able to properly handle situation when there is node.js but without coffee-script and it shall switch to Rhino.
Version 0.8 works (just the result of compilation is still empty file)

---

2013-02-26 10:57:08,575 [main] INFO  compiler.CoffeeCompilerManager  - Compiling CoffeeScript path src/coffee/app to web-app/js/app
2013-02-26 10:57:08,598 [main] INFO  compiler.CoffeeCompiler  - Purging web-app/js/app...
| Error 2013-02-26 10:57:09,208 [pool-4-thread-1] ERROR processor.NodeCoffeeScriptProcessor  - exitStatus: 1
2013-02-26 10:57:09,236 [pool-4-thread-1] WARN  processor.NodeCoffeeScriptProcessor  - Exception while applying NodeCoffeeScriptProcessor processor on the src\coffee\app\user_index.coffee resource, no
 processing applied...
Message: Error in CoffeeScript:
'coffee' is not recognized as an internal or external command,
operable program or batch file.

```
Line | Method
```

->>  101 | processData in org.grails.plugins.coffee.compiler.processor.NodeCoffeeScriptProcessor

---

|     69 | process     in     ''
|     87 | process . . in ro.isdc.wro.model.resource.processor.decorator.ProcessorDecorator
|     72 | process     in org.grails.plugins.coffee.compiler.processor.CoffeeScriptProcessor
|     68 | compileFile in org.grails.plugins.coffee.compiler.CoffeeCompiler
|    125 | doCall      in org.grails.plugins.coffee.compiler.CoffeeCompiler$_compileAll_closure2_closure6
|    334 | innerRun .  in java.util.concurrent.FutureTask$Sync
|    166 | run         in java.util.concurrent.FutureTask
|   1145 | runWorker . in java.util.concurrent.ThreadPoolExecutor
|    615 | run         in java.util.concurrent.ThreadPoolExecutor$Worker
^    722 | run . . . . in java.lang.Thread
| Error 2013-02-26 10:57:09,282 [pool-4-thread-1] ERROR processor.NodeCoffeeScriptProcessor  - Error in CoffeeScript:
'coffee' is not recognized as an internal or external command,
operable program or batch file.

Message: Error in CoffeeScript:
'coffee' is not recognized as an internal or external command,
operable program or batch file.

```
Line | Method
```

->>  101 | processData in org.grails.plugins.coffee.compiler.processor.NodeCoffeeScriptProcessor

---

|     69 | process     in     ''
|     87 | process . . in ro.isdc.wro.model.resource.processor.decorator.ProcessorDecorator
|     72 | process     in org.grails.plugins.coffee.compiler.processor.CoffeeScriptProcessor
|     68 | compileFile in org.grails.plugins.coffee.compiler.CoffeeCompiler
|    125 | doCall      in org.grails.plugins.coffee.compiler.CoffeeCompiler$_compileAll_closure2_closure6
|    334 | innerRun .  in java.util.concurrent.FutureTask$Sync
|    166 | run         in java.util.concurrent.FutureTask
|   1145 | runWorker . in java.util.concurrent.ThreadPoolExecutor
|    615 | run         in java.util.concurrent.ThreadPoolExecutor$Worker
^    722 | run . . . . in java.lang.Thread
| Error 2013-02-26 10:57:09,304 [pool-4-thread-1] ERROR compiler.CoffeeCompiler  - Error in CoffeeScript:
'coffee' is not recognized as an internal or external command,
operable program or batch file.
 in src\coffee\app\user_index.coffee
| Running Grails application
| Error 2013-02-26 10:57:19,061 [localhost-startStop-1] ERROR resource.ResourceMeta  - Resource not found: /js/app/user_index.js
| Server running. Browse to http://localhost:8080/RhinoTest

**Comment by brian428** [comment] 2013-02-26 14:27
Sorry, I saw 1.6 in the grails.project.target and source level in the config and assumed that was the Grails version. 

Hmm, I'll try to set things up to match exactly your JRE and Grails version to figure out if it could be one of those.

**Comment by brian428** [comment] 2013-02-27 00:45
OK the key to reproducing the error seems to be using Grails 2.2 (which uses Groovy 2.0). The issue appears to be somewhere in the Wro4J Rhino processor that the plugin uses. I'll see if I can dig into it further, but my fear is that it may mean that folks on 2.2 need to have Node CoffeeScript installed and go through the Node processor until/unless Wro4J is updated/fixed. :-/

**Comment by ctoestreich** [comment] 2013-02-27 03:16
Keep in mind my copy and paste of the actual rhino processor.  You may want to try without my changes.

**Comment by brian428** [comment] 2013-03-01 02:34
Christian, I've tried to dig around and figure out what's up with this, but I'm drawing a blank. I think it has to be something in the changed/overridden Wro4J processor classes that you added. It's strange, because as far as I can see your overridden Rhino processor is almost exactly the same as the original Wro4J one, aside from the wrapJS flag. Still, if I remove the overridden classes and revert back to Wro4J 1.6.0, everything works using Grails 2.2. I'm also trying it with Wro4J 1.6.2 but am hitting an error on one specific test method, so I'm not sure if that could also have something to do with it, or if it's a separate issue. I'll keep testing to see if I can tell if the version of Wro4J matters.

Anyway, with the custom classes pulled out, the wrapJS option obviously goes away. I've left in your addition of the purgeJS and overrideJS option since that works independently of the Wro4J bits.

I wanted to see what you think. If you have time soon to try and figure out what's up, let me know. If you think it may be a while, or you're also unable to pinpoint what's breaking, I'll push an update that removes the wrapJS and the custom classes so that at least things work on Grails 2.2.

**Comment by ctoestreich** [comment] 2013-03-01 05:07
Will do on monday.

**Comment by brian428** [comment] 2013-03-01 05:10
Just FYI I don't think the Wro4J version is actually the cause. I was getting a weird error on one single test with 1.6.2, and only when using CoffeeScriptProcessor and not forcing RhinoCoffeeScriptProcessor. I'm still not sure what the deal is since the same behavior works fine when running it in a live app, so not sure what's up there. Just thought I'd let you know to (hopefully) eliminate one possible source of the issue.

**Closed as completed** 2013-03-06 16:11 UTC

**Comment by brian428** [comment] 2013-03-06 16:13
@martindobias give the new 0.9 version a try. Everything works ok for me now on both Grails 2.1 and 2.2.

**Comment by martindobias** [comment] 2013-03-07 21:30
Haven't had time for proper testing, just a quick feedback.
Compiling now works even without node.js and its coffee-script plugin, thanks a lot @brian428 !

Though, another issue appeared. Now the coffee files are compiled twice, once to the default output directory and once to the directory of my choice.

My **Config.groovy** file has:

``` groovy
"coffeescript-compiler" {
    pluginConfig {
        wrapJS = false
    }
    appSource {
        coffeeSourcePath = "src/coffee"
        jsOutputPath = "web-app/cs"
    }
}
```

and this is what I get:
2013-03-07 22:09:04,177 [main] INFO  compiler.CoffeeCompilerManager  - Compiling CoffeeScript path src/coffee to **web-app/js/app**
2013-03-07 22:09:05,033 [pool-4-thread-1] INFO  compiler.CoffeeCompiler  - Compiling  src\coffee\main_index.coffee to web-app\js\app\main_index.js
2013-03-07 22:09:05,033 [pool-4-thread-2] INFO  compiler.CoffeeCompiler  - Compiling  src\coffee\user_index.coffee to web-app\js\app\user_index.js
2013-03-07 22:09:11,411 [main] INFO  compiler.CoffeeCompilerManager  - Compiling CoffeeScript path src/coffee to **web-app/cs**
2013-03-07 22:09:11,457 [pool-5-thread-1] INFO  compiler.CoffeeCompiler  - Compiling  src\coffee\main_index.coffee to web-app\cs\main_index.js
2013-03-07 22:09:11,457 [pool-5-thread-2] INFO  compiler.CoffeeCompiler  - Compiling  src\coffee\user_index.coffee to web-app\cs\user_index.js

Shall I open this as a new issue?

**Comment by brian428** [comment] 2013-03-07 22:05
Yes, please do. Thanks.
